# Generated by Django 5.0.7 on 2024-10-01 13:20

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to=myauth.models.product_images_directory_path),
            preserve_default=False,
        ),
    ]
