# Generated by Django 5.0.7 on 2024-10-01 14:35

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=myauth.models.product_images_directory_path),
        ),
    ]
