# Generated by Django 5.0.7 on 2024-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
