# Generated by Django 5.0.7 on 2024-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_product_available_for_sale_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_for_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
